export const NAVIGATION_ITEMS = {
  HOME: "home",
  WORK: "work",
  SKILLS: "skills",
  CONTACT: "contact",
  ABOUT: "about",
};
export const NAVIGATION_ITEMS_LIST = [
  NAVIGATION_ITEMS.HOME,
  NAVIGATION_ITEMS.SKILLS,
  NAVIGATION_ITEMS.WORK,
  NAVIGATION_ITEMS.ABOUT,
];
